name: Publish Python package to Artifactory

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  publish:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure PATH
        run: echo "/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Verify Python & uv
        run: |
          python3 --version
          uv --version

      - name: Build package
        working-directory: my-python-package
        run: |
          uv build
      - name: Curl connectivity test
        run: |
          curl -vk http://localhost:8081/artifactory/api/system/ping

    
